-- Import karyawan awal. Kode EMP-EMP-* sudah dinormalisasi.
INSERT INTO staff (name, employee_code, role, branch_id, referral_code, status) VALUES
('Rendi Suryadi','EMP-1','guru',NULL,'RS-1001','aktif'),
('Rita Rosanti','EMP-2','guru',NULL,'RR-1002','aktif'),
('Jeehan Humaira','EMP-4','guru',NULL,'JH-1004','aktif'),
('Yolandari','EMP-18','guru',NULL,'YOLA-1018','aktif'),
('Rangga Satria Wardhana','EMP-32','guru',NULL,'RSW-1032','aktif'),
('Danisyana',NULL,'guru',NULL,'DANI-1006','aktif'),
('Rini Indriani','EMP-50','guru',NULL,'RI-1050','aktif'),
('Erna Rahayuningsih','EMP-54','guru',NULL,'ER-1054','aktif'),
('Widya Salsabila Hamidah','EMP-58','guru',NULL,'WSH-1058','aktif'),
('Mici Ardila','EMP-61','guru',NULL,'MA-1061','aktif'),
('Jesikaratna Sari','EMP-39','guru',NULL,'JS-1039','aktif'),
('Irin','EMP-62','guru',NULL,'IRIN-1062','aktif'),
('Nurkholis Majid','EMP-63','guru',NULL,'NM-1063','aktif'),
('Denisa Nur Rizki','EMP-65','guru',NULL,'DNR-1065','aktif'),
('Yuli Yanti','EMP-73','guru',NULL,'YY-1073','aktif'),
('Marthila Wahyu Novita','EMP-74','guru',NULL,'MWN-1074','aktif'),
('Lintang Hari Tanhanasashi Purnama','EMP-76','guru',NULL,'LHTP-1076','aktif'),
('Diki Aryanto','EMP-82','guru',NULL,'DA-1082','aktif'),
('Thariq Aulia Al Hakim','EMP-84','guru',NULL,'TAAH-1084','aktif'),
('Maulana Riksa','EMP-88','guru',NULL,'MR-1088','aktif'),
('Nina Irvani','EMP-89','guru',NULL,'NI-1089','aktif'),
('Andri Susanto','EMP-95','guru',NULL,'AS-1095','aktif'),
('Luthvinia Alawiah','EMP-96','guru',NULL,'LA-1096','aktif'),
('Nella Aulia Asyadah','EMP-104','guru',NULL,'NAA-1104','aktif'),
('Adistiyani','EMP-107','guru',NULL,'ADIS-1107','aktif'),
('Bagas Dany Aradhana','EMP-108','guru',NULL,'BDA-1108','aktif'),
('Isna Fatihatul Mujahidah','EMP-37','guru',NULL,'IFM-1037','aktif'),
('Arissa Zahwa Ramadhani','EMP-118','guru',NULL,'AZR-1118','aktif'),
('Muthia Syafwa Nabillah','EMP-121','guru',NULL,'MSN-1121','aktif'),
('Dani','EMP-122','guru',NULL,'DANI-1122','aktif'),
('Hanifah Nuraviantari Putri Hendarto','EMP-124','guru',NULL,'HNPH-1124','aktif'),
('Naja Eiko Khalisa','EMP-7','guru',NULL,'NEK-1007','aktif'),
('Ratu Balqis Fatya Pebrinda Lubis','EMP-128','guru',NULL,'RBFL-1128','aktif'),
('Hikmah Nuraini','EMP-130','guru',NULL,'HN-1130','aktif'),
('Bayu Aji Prihantoro','EMP-132','guru',NULL,'BAP-1132','aktif'),
('Ade Sekar Fabry Lianda','EMP-134','guru',NULL,'ASFL-1134','aktif'),
('Alia Aprilina','EMP-135','guru',NULL,'AA-1135','aktif'),
('Yuni Adelia','EMP-136','guru',NULL,'YA-1136','aktif'),
('Destiana Praditya Ningrum','EMP-137','guru',NULL,'DPN-1137','aktif'),
('Liena Asma " Abiedatul Mufiedah','EMP-138','guru',NULL,'LAAM-1138','aktif'),
('Najwa Nuraini','EMP-139','guru',NULL,'NN-1139','aktif'),
('Nikita Pramodya Az - Zahra','EMP-140','guru',NULL,'NPAZ-1140','aktif'),
('Novilla Viandra','EMP-142','guru',NULL,'NV-1142','aktif'),
('Nur Annisa','EMP-143','guru',NULL,'NA-1143','aktif'),
('Rahmania Fionna','EMP-144','guru',NULL,'RF-1144','aktif'),
('Nathan Mahesa Dewanto','EMP-145','guru',NULL,'NMD-1145','aktif'),
('Aulia Shafira','EMP-146','guru',NULL,'AS-1146','aktif'),
('Salfira Salsabila','EMP-147','guru',NULL,'SS-1147','aktif'),
('Valerie Nathaviana Ndun','EMP-148','guru',NULL,'VNN-1148','aktif');
